// AUTO-GENERATED by scripts/build-legacy-idt-odt.mjs — DO NOT EDIT BY HAND.
// Shared camera/log helpers for the legacy IDT/ODT variant sources
// (idtOdtSources.ts), deduped + emitted once. Always included; the active
// (selected) IDT/ODT source calls these by bare name. MUST follow <acesPipeline>
// (pu/sn/nn/en/qf/Kf) + <colorPipeline> + <cubeAtlas>. See [[legacy-look-needs-aces-rrt-odt]].
// helper: on

  float vGamma(float x) {
    float nx = 1.0 - x;
    return nx * pow(x, 0.7654321) + x * (1.0 - pow(nx, 0.7654321));
  }
  vec3 vGamma(vec3 rgb) {
    return vec3(vGamma(rgb.x), vGamma(rgb.y), vGamma(rgb.z));
  }

// helper: wn

  float vc_lg10(float x) {
    float y = (x - 0.1) / (0.1 - 6.0);
    y = y * y * y * (y * (6.0 * y - 15.0) + 10.0);
    float s = mix(x + (x - (x * x * (3.0 - 2.0 * x))), y, 0.95);
    return mix(s, mix(1.0 - pow(1.0 - x, x * 2.0), 0.18 * (pow(10.0, (x - 0.4150634) / 0.2756705) - 0.0280665), x / 2.0), x);
  }
  vec3 vc_lg10(vec3 c) {
    return vec3(vc_lg10(c.x), vc_lg10(c.y), vc_lg10(c.z));
  }

// helper: Gn

  float CanonLog_to_linear(float clog) {
    if (clog < 0.12512248)
      return -(pow(10.0, (0.12512248 - clog) / 0.45310179) - 1.0) / 10.1596;
    else
      return (pow(10.0, (clog - 0.12512248) / 0.45310179) - 1.0) / 10.1596;
  }

// helper: Vn

  float CanonLog2_to_linear(float clog2) {
    if(clog2 < 0.092864125)
      return -(pow(10.0, (0.092864125 - clog2) / 0.24136077) - 1.0) / 87.099375;
    else
      return (pow(10.0, (clog2 - 0.092864125) / 0.24136077) - 1.0) / 87.099375;
  }

// helper: $n

  float CanonLog3_to_linear (float clog3) {
    if (clog3 < 0.097465473)
      return -(pow(10.0, (0.12783901 - clog3) / 0.36726845) - 1.0) / 14.98325;
    else if (clog3 <= 0.15277891)
      return (clog3 - 0.12512219) / 1.9754798;
    else
      return (pow( 10.0, (clog3 - 0.12240537) / 0.36726845) - 1.0) / 14.98325;
  }

// helper: le

  float SLog2_to_lin(float SLog, float b, float ab, float w) {
    if (SLog >= ab) {
      return (219.0 * (pow(10.0, (((SLog - b) / (w - b) - 0.616596 - 0.03) / 0.432699)) - 0.037584) / 155.0) * 0.9;
    } else if (SLog < ab) {
      return (((SLog - b) / (w - b) - 0.030001222851889303) / 3.53881278538813) * 0.9;
    } else {
      return 0.0;
    }
  }

// helper: ue

  float SLog3_to_linear(float SLog) {
    if (SLog >= 171.2102946929 / 1023.0) {
      return pow(10.0, (SLog * 1023.0 - 420.0) / 261.5) * (0.18 + 0.01) - 0.01;
    } else {
      return (SLog * 1023.0 - 95.0) * 0.01125000 / (171.2102946929 - 95.0);
    }
  }

// helper: an

  float CineonToLinear(float x) {
    const float n_gamma = 0.6;
    const float black_point = 95.0 / 1023.0;
    const float white_point = 685.0 / 1023.0;
    const float code_value_to_density = 0.002 * 1023.0;
    const float black_linear = pow(10.0, (black_point - white_point) * (code_value_to_density / n_gamma));
    float code_linear = pow(10.0, (x - white_point) * (code_value_to_density / n_gamma));
    return (code_linear - black_linear) / (1.0 - black_linear);
  }
  vec3 CineonToLinear(vec3 rgb) {
    return vec3(CineonToLinear(rgb.x), CineonToLinear(rgb.y), CineonToLinear(rgb.z));
  }

// helper: vd

  float inv_normalizedLogC4ToRelativeSceneLinear(float y) {
    const float a = (pow(2.0, 18.0) - 16.0) / 117.45;
    const float b = (1023.0 - 95.0) / 1023.0;
    const float c = 95.0 / 1023.0;
    const float s = (7.0 * log(2.0) * pow(2.0, 7.0 - 14.0 * c / b)) / (a * b);
    const float t = (pow(2.0, 14.0 * (-c / b) + 6.0) - 64.0) / a;
    return y < (0.0 * s + t) ? (y - t) / s : c + b * (log2(y * a + 64.0) - 6.0) / 14.0;
  }

