// AUTO-GENERATED by scripts/build-legacy-idt-odt.mjs — DO NOT EDIT BY HAND.
// Legacy Poto input (IDT) + display (ODT) color-space metadata: the int index
// each id maps to in the GLSL dispatch (legacyDispatchIDT/ODT), the optional cube
// LUT filename, and the grouped menu taxonomy for the selector dropdowns.

export type ColorSpaceEntry = { id: string; index: number; lut: string | null };
export type ColorSpaceMenu = { group: string; options: { id: string; label: string }[] };

export const IDT_COLOR_SPACES: ColorSpaceEntry[] = [
  { id: "sRGB", index: 0, lut: null },
  { id: "FilmNegative", index: 1, lut: null },
  { id: "Rec709", index: 2, lut: null },
  { id: "Rec2020", index: 3, lut: null },
  { id: "AdobeRGB", index: 4, lut: null },
  { id: "P3D60_CSC", index: 5, lut: null },
  { id: "P3D65_CSC", index: 6, lut: null },
  { id: "DisplayP3_IDT", index: 7, lut: null },
  { id: "EXR_IDT", index: 8, lut: null },
  { id: "Cineon_IDT", index: 9, lut: null },
  { id: "ProPhotoRGB", index: 10, lut: null },
  { id: "VisionLogFlat", index: 11, lut: null },
  { id: "VisionLog", index: 12, lut: null },
  { id: "VisionLogFilmNegative", index: 13, lut: null },
  { id: "ArriLogC", index: 14, lut: null },
  { id: "ArriLogC_NO_VGAMMA", index: 15, lut: null },
  { id: "ArriAlexa35", index: 16, lut: null },
  { id: "ArriAlexa35_NO_VGAMMA", index: 17, lut: null },
  {
    id: "BMD_Cinema_Camera_Film",
    index: 18,
    lut: "BMD_CinemaCamera_Film_to_ACEScct_CUBE64_RGB16.json",
  },
  { id: "BMD_4_6k_Film", index: 19, lut: "BMD_4_6k_Film_to_ACEScct_CUBE64_RGB16.json" },
  { id: "BMD_4k_Film", index: 20, lut: "BMD_4k_Film_to_ACEScct_CUBE64_RGB16.json" },
  { id: "BMD_Pocket_4k_Film", index: 21, lut: "BMD_Pocket_Film_to_ACEScct_CUBE64_RGB16.json" },
  { id: "BMD_Pocket_6k_Film", index: 22, lut: "BMD_Pocket_6k_Film_to_ACEScct_CUBE64_RGB16.json" },
  {
    id: "BMD_Broadcast_Film",
    index: 23,
    lut: "BMD_Broadcast_Film_v4_to_ACEScct_CUBE64_RGB16.json",
  },
  { id: "BlackMagicDesignWideGamutGen5", index: 24, lut: null },
  { id: "BolexLogWideGamutRGB", index: 25, lut: null },
  { id: "CanonLogBT2020_Daylight", index: 26, lut: null },
  { id: "CanonLogBT2020_Tungsten", index: 27, lut: null },
  { id: "CanonLogCinemaGamut_Daylight", index: 28, lut: null },
  { id: "CanonLogCinemaGamut_Tungsten", index: 29, lut: null },
  { id: "CanonLog2BT2020_Daylight", index: 30, lut: null },
  { id: "CanonLog2BT2020_Tungsten", index: 31, lut: null },
  { id: "CanonLog2CinemaGamut_Daylight", index: 32, lut: null },
  { id: "CanonLog2CinemaGamut_Tungsten", index: 33, lut: null },
  { id: "CanonLog3BT2020_Daylight", index: 34, lut: null },
  { id: "CanonLog3BT2020_Tungsten", index: 35, lut: null },
  { id: "CanonLog3CinemaGamut_Daylight", index: 36, lut: null },
  { id: "CanonLog3CinemaGamut_Tungsten", index: 37, lut: null },
  { id: "DJI_DLogDGamut", index: 38, lut: null },
  { id: "DJI_DLogMDGamut", index: 39, lut: null },
  { id: "Fuji_FLogFGamut", index: 40, lut: null },
  { id: "FujiFLog2FGamut", index: 41, lut: null },
  { id: "GoPro_ProTuneFlat", index: 42, lut: null },
  { id: "Kinefinity_KineLog3", index: 43, lut: null },
  { id: "Nikon_NLogBT2020", index: 44, lut: null },
  { id: "OM_Log_BT2020", index: 45, lut: "OM_LOG400_BT2020_to_ACEScct_CUBE64_RGB16.json" },
  { id: "OM_Log_P3D65", index: 46, lut: "OM_LOG400_P3_to_ACEScct_CUBE64_RGB16.json" },
  { id: "Sony_SLogSGamut", index: 47, lut: null },
  { id: "Sony_SLog2SGamut_Daylight", index: 48, lut: null },
  { id: "Sony_SLog2SGamut_Tungsten", index: 49, lut: null },
  { id: "Sony_SLog3SGamut3", index: 50, lut: null },
  { id: "Sony_SLog3SGamut3_Cine", index: 51, lut: null },
  { id: "Sony_Venice_SLog3SGamut3", index: 52, lut: null },
  { id: "Sony_Venice_SLog3SGamut3_Cine", index: 53, lut: null },
  { id: "Panasonic_VLogVGamut", index: 54, lut: null },
  { id: "REDLogFilmDragonColor", index: 55, lut: null },
  { id: "REDLogFilmDragonColor2", index: 56, lut: null },
  { id: "REDLogFilmRedColor", index: 57, lut: null },
  { id: "REDLogFilmRedColor2", index: 58, lut: null },
  { id: "RedLogFilmRedColor3", index: 59, lut: null },
  { id: "RedLogFilmRedColor4", index: 60, lut: null },
  { id: "RedLog3G10WideGamutRGB", index: 61, lut: null },
  { id: "RedLog3G10WideGamutRGB_NO_VGAMMA", index: 62, lut: null },
  { id: "ZCam_ZLog2", index: 63, lut: null },
  { id: "LeicaLLog", index: 64, lut: null },
  { id: "AppleHLG", index: 65, lut: null },
  { id: "AppleLog", index: 66, lut: null },
  { id: "FILM_ADX10", index: 67, lut: null },
  { id: "FILM_ADX16", index: 68, lut: null },
  { id: "ACES_2065_1", index: 69, lut: null },
  { id: "ACES_CC", index: 70, lut: null },
  { id: "ACES_CCT", index: 71, lut: null },
  { id: "ACES_CCT_VGAMMA", index: 72, lut: null },
  { id: "ACES_CG", index: 73, lut: null },
  { id: "DaVinci_WideGamut_IDT", index: 74, lut: null },
  { id: "DaVinci_WideGamut_VGAMMA_IDT", index: 75, lut: null },
];

export const ODT_COLOR_SPACES: ColorSpaceEntry[] = [
  { id: "sRGB", index: 0, lut: null },
  { id: "Rec709", index: 1, lut: null },
  { id: "Rec2020", index: 2, lut: null },
  { id: "Rec2020_ST2084_HDR", index: 3, lut: null },
  { id: "AdobeRGB", index: 4, lut: null },
  { id: "ProPhotoRGB", index: 5, lut: null },
  { id: "P3_DCI_D60", index: 6, lut: null },
  { id: "P3_DCI_D65", index: 7, lut: null },
  { id: "P3D60", index: 8, lut: null },
  { id: "P3D65", index: 9, lut: null },
  { id: "DisplayP3_ODT", index: 10, lut: null },
  { id: "ACES_2065_1", index: 11, lut: null },
  { id: "ACES_CC", index: 12, lut: null },
  { id: "ACES_CCT", index: 13, lut: null },
  { id: "ACES_CG", index: 14, lut: null },
  { id: "P3D60_CSC", index: 15, lut: null },
  { id: "P3D65_CSC", index: 16, lut: null },
  { id: "DaVinci_WideGamut_ODT", index: 17, lut: "ACEScct-to-DWG-CUBE64_RGB16.json" },
  { id: "RED_Log3G10_WideGamutRGB", index: 18, lut: null },
  { id: "ArriLogC3", index: 19, lut: null },
  { id: "ArriLogC4", index: 20, lut: null },
  { id: "ArriRec709", index: 21, lut: "LogC4-to-Rec709-CUBE64_RGB16.json" },
  { id: "ArriRec2020", index: 22, lut: "LogC4-to-Rec2020-CUBE64_RGB16.json" },
  { id: "Kodak2383_ACEScct", index: 23, lut: "ACEScct-to-2383-ACEScct-CUBE64_RGB16.json" },
  { id: "Kodak2383_Rec709", index: 24, lut: "ACEScct-to-2383-ACEScct-CUBE64_RGB16.json" },
];

export const IDT_MENU: ColorSpaceMenu[] = [
  {
    group: "Generic",
    options: [
      { id: "sRGB", label: "sRGB" },
      { id: "Rec709", label: "Rec709" },
      { id: "Rec2020", label: "Rec2020" },
      { id: "AdobeRGB", label: "Adobe RGB" },
      { id: "ProPhotoRGB", label: "ProPhoto RGB" },
      { id: "DisplayP3_IDT", label: "Display P3" },
      { id: "P3D60_CSC", label: "P3 (D60)" },
      { id: "P3D65_CSC", label: "P3 (D65)" },
      { id: "Cineon_IDT", label: "Cineon (709)" },
      { id: "EXR_IDT", label: "EXR (709)" },
      { id: "ACES_CCT", label: "ACEScct" },
      { id: "DaVinci_WideGamut_IDT", label: "DaVinci Wide Gamut Intermediate" },
    ],
  },
  {
    group: "Raw Development",
    options: [
      { id: "VisionLog", label: "RAW Standard" },
      { id: "VisionLogFlat", label: "RAW Flat" },
    ],
  },
  {
    group: "Analog Film",
    options: [
      { id: "FilmNegative", label: "Film Negative" },
      { id: "VisionLogFilmNegative", label: "RAW Film Negative" },
    ],
  },
  {
    group: "Arri",
    options: [
      { id: "ArriLogC", label: "Arri Log-C v3" },
      { id: "ArriAlexa35", label: "Arri Log-C v4" },
    ],
  },
  {
    group: "Apple",
    options: [
      { id: "AppleLog", label: "Apple ProRes Log" },
      { id: "AppleHLG", label: "Apple ProRes HDR" },
    ],
  },
  {
    group: "Blackmagic Design",
    options: [
      { id: "BlackMagicDesignWideGamutGen5", label: "BMDFilm WideGamut Gen. 5" },
      { id: "BMD_4k_Film", label: "BMDFilm 4k" },
      { id: "BMD_4_6k_Film", label: "BMDFilm 4.6k" },
      { id: "BMD_Pocket_4k_Film", label: "BMDFilm Pocket 4k" },
      { id: "BMD_Pocket_6k_Film", label: "BMDFilm Pocket 6k" },
      { id: "BMD_Broadcast_Film", label: "BMDFilm Broadcast" },
      { id: "BMD_Cinema_Camera_Film", label: "BMDFilm Cinema Camera" },
    ],
  },
  { group: "Bolex", options: [{ id: "BolexLogWideGamutRGB", label: "BolexLog WideGamutRGB" }] },
  {
    group: "Canon",
    options: [
      { id: "CanonLogBT2020_Daylight", label: "CanonLog BT2020 (Daylight)" },
      { id: "CanonLogBT2020_Tungsten", label: "CanonLog BT2020 (Tungsten)" },
      { id: "CanonLogCinemaGamut_Daylight", label: "CanonLog CinemaGamut (Daylight)" },
      { id: "CanonLogCinemaGamut_Tungsten", label: "CanonLog CinemaGamut (Tungsten)" },
      { id: "CanonLog2BT2020_Daylight", label: "CanonLog2 BT2020 (Daylight)" },
      { id: "CanonLog2BT2020_Tungsten", label: "CanonLog2 BT2020 (Tungsten)" },
      { id: "CanonLog2CinemaGamut_Daylight", label: "CanonLog2 CinemaGamut (Daylight)" },
      { id: "CanonLog2CinemaGamut_Tungsten", label: "CanonLog2 CinemaGamut (Tungsten)" },
      { id: "CanonLog3BT2020_Daylight", label: "CanonLog3 BT2020 (Daylight)" },
      { id: "CanonLog3BT2020_Tungsten", label: "CanonLog3 BT2020 (Tungsten)" },
      { id: "CanonLog3CinemaGamut_Daylight", label: "CanonLog3 CinemaGamut (Daylight)" },
      { id: "CanonLog3CinemaGamut_Tungsten", label: "CanonLog3 CinemaGamut (Tungsten)" },
    ],
  },
  {
    group: "DJI",
    options: [
      { id: "DJI_DLogDGamut", label: "D-LOG D-Gamut" },
      { id: "DJI_DLogMDGamut", label: "D-LOG M D-Gamut" },
    ],
  },
  {
    group: "Fuji",
    options: [
      { id: "Fuji_FLogFGamut", label: "F-LOG F-Gamut" },
      { id: "FujiFLog2FGamut", label: "F-LOG2 F-Gamut" },
    ],
  },
  { group: "GoPro", options: [{ id: "GoPro_ProTuneFlat", label: "ProTune Flat" }] },
  { group: "Kinefinity", options: [{ id: "Kinefinity_KineLog3", label: "KineLog3" }] },
  { group: "Leica", options: [{ id: "LeicaLLog", label: "L-Log BT2020" }] },
  { group: "Nikon", options: [{ id: "Nikon_NLogBT2020", label: "N-LOG BT2020" }] },
  {
    group: "Olympus / OM System",
    options: [
      { id: "OM_Log_BT2020", label: "OM-Log 400 BT2020" },
      { id: "OM_Log_P3D65", label: "OM-Log 400 P3-D65" },
    ],
  },
  {
    group: "Sony",
    options: [
      { id: "Sony_SLogSGamut", label: "S-Log S-Gamut" },
      { id: "Sony_SLog2SGamut_Daylight", label: "S-Log2 S-Gamut (Daylight)" },
      { id: "Sony_SLog2SGamut_Tungsten", label: "S-Log2 S-Gamut (Tungsten)" },
      { id: "Sony_SLog3SGamut3", label: "S-Log3 S-Gamut3" },
      { id: "Sony_SLog3SGamut3_Cine", label: "S-Log3 S-Gamut3.Cine" },
      { id: "Sony_Venice_SLog3SGamut3", label: "Venice S-Log3 S-Gamut3" },
      { id: "Sony_Venice_SLog3SGamut3_Cine", label: "Venice S-Log3 S-Gamut3.Cine" },
    ],
  },
  { group: "Panasonic", options: [{ id: "Panasonic_VLogVGamut", label: "V-Log V-Gamut" }] },
  {
    group: "RED",
    options: [
      { id: "RedLog3G10WideGamutRGB", label: "LOG3G10 REDWideGamutRGB" },
      { id: "REDLogFilmDragonColor", label: "REDLogFilm DragonColor" },
      { id: "REDLogFilmDragonColor2", label: "REDLogFilm DragonColor2" },
      { id: "REDLogFilmRedColor", label: "REDLogFilm REDColor" },
      { id: "REDLogFilmRedColor2", label: "REDLogFilm REDColor2" },
      { id: "RedLogFilmRedColor3", label: "REDLogFilm REDColor3" },
      { id: "RedLogFilmRedColor4", label: "REDLogFilm REDColor4" },
    ],
  },
  { group: "ZCam", options: [{ id: "ZCam_ZLog2", label: "Z-Log2" }] },
];

export const ODT_MENU: ColorSpaceMenu[] = [
  {
    group: "SDR Display",
    options: [
      { id: "sRGB", label: "sRGB" },
      { id: "Rec709", label: "Rec709" },
      { id: "Rec2020", label: "Rec2020" },
      { id: "AdobeRGB", label: "Adobe RGB" },
      { id: "DisplayP3_ODT", label: "Display P3" },
      { id: "P3D60_CSC", label: "P3 (D60)" },
      { id: "P3D65_CSC", label: "P3 (D65)" },
    ],
  },
  {
    group: "HDR & Cinema",
    options: [
      { id: "Rec2020_ST2084_HDR", label: "HDR Display (BT2020-ST2084)" },
      { id: "P3_DCI_D60", label: "DCI-P3 Projector (D60)" },
      { id: "P3_DCI_D65", label: "DCI-P3 Projector (D65)" },
    ],
  },
  {
    group: "Cinema Cameras",
    options: [
      { id: "ArriLogC4", label: "Arri Log-C v4" },
      { id: "ArriRec709", label: "Arri REC 709 (SDR)" },
      { id: "ArriRec2020", label: "Arri REC 2020 (SDR)" },
      { id: "RED_Log3G10_WideGamutRGB", label: "RED LOG3G10" },
    ],
  },
  {
    group: "Print Film Emulation",
    options: [
      { id: "Kodak2383_Rec709", label: "Kodak 2383 Rec709" },
      { id: "Kodak2383_ACEScct", label: "Kodak 2383 ACEScct" },
    ],
  },
];

const idtById = new Map(IDT_COLOR_SPACES.map((s) => [s.id, s]));
const odtById = new Map(ODT_COLOR_SPACES.map((s) => [s.id, s]));

export function inputTransformIndex(id: string): number {
  return idtById.get(id)?.index ?? 0;
}
export function displayTransformIndex(id: string): number {
  return odtById.get(id)?.index ?? 0;
}
export function inputTransformLut(id: string): string | null {
  return idtById.get(id)?.lut ?? null;
}
export function displayTransformLut(id: string): string | null {
  return odtById.get(id)?.lut ?? null;
}
export function isInputTransformId(id: string): boolean {
  return idtById.has(id);
}
export function isDisplayTransformId(id: string): boolean {
  return odtById.has(id);
}
