// Color Match (legacy `je` state). A reference-image color transfer baked into the
// look as a 16³ LUT generated by the srp-static algorithm (see ColorMatchService).
// The "AI" framing is legacy marketing — it is deterministic statistics.

/** Sentinel reference id for the "bypass" tile (no match). */
export const BYPASS_REFERENCE_ID = "__bypass__";

export type MatchStatus = "idle" | "analyzing" | "active" | "error";

export type MatchState = {
  /** Built-in name (e.g. "match_ref_3.webp"), an imported id, or BYPASS_REFERENCE_ID. */
  referenceId: string;
  referenceName?: string;
  /** Legacy c.sourceID: the source media id used when the LUT was generated. */
  sourceId: string;
  /** Legacy c.sourceIDT: input transform used when the LUT was generated. */
  sourceIdt: string;
  /** Runtime source fingerprint for current cache dimensions + IDT. */
  sourceSignature: string;
  colorMix: number; // 0..1 — Color slider (amount of color to match)
  lumaMix: number; // 0..1 — Tone slider (amount of brightness/contrast to match)
  /** Baked 16³ half-float RGB LUT, srp order (r + g*16 + b*256)*3. null = no match. */
  lut: number[] | null;
  /** Bumped each time a new LUT is generated; drives the LUTGenerator atlas upload. */
  generatedAt: number;
  /** Hide the match without discarding it (legacy bypass tile). */
  bypass: boolean;
  status: MatchStatus;
  error?: string;
};

export const DEFAULT_MATCH_STATE: MatchState = {
  referenceId: BYPASS_REFERENCE_ID,
  referenceName: undefined,
  sourceId: "",
  sourceIdt: "sRGB",
  sourceSignature: "",
  colorMix: 1,
  lumaMix: 1,
  lut: null,
  generatedAt: 0,
  bypass: false,
  status: "idle",
  error: undefined,
};

/** True when the match should actually affect the image. */
export function isMatchActive(state: MatchState): boolean {
  return (
    !state.bypass &&
    !!state.lut &&
    state.lut.length > 0 &&
    state.referenceId !== BYPASS_REFERENCE_ID
  );
}

export function cloneMatchState(state: MatchState): MatchState {
  return { ...state, lut: state.lut ? state.lut.slice() : null };
}
