/*
 * Legacy LUT-export format writers (package.min.js: mm/_m/vm/wm/bm/Cm/Im + Tm/Am/Em).
 *
 * Each writer takes a baked 64³ RGB grid (the engine's global-color LUT read back as
 * Float32 RGB, r-fastest / blue-major), resamples it to the requested size with the
 * same trilinear resampler legacy `dm()` uses (lutDataFromBakedLUT), then serialises it
 * in the destination's exact byte layout. Layouts and index math are ported verbatim —
 * not guessed.
 *
 * Adobe Lightroom/Camera-RAW XMP uses the legacy `ubitmap.wasm` DCP encoder through
 * XmpProfileClient, matching the legacy `gm` worker path.
 */
import { lutDataFromBakedLUT, type BakedLUTReadback } from "../interchange/LUTData";
import type { ExportColorSpace } from "../passes/ExportPass";
import { encodeXmpProfile } from "./XmpProfileClient";

/** PNG texture layout (the part after "png-" in the legacy lut-format value). */
export type LutLayout = "cube" | "grid" | "strip" | "c4d";

export type LutWriteSettings = {
  /** Destination file extension incl. dot, e.g. ".cube" / ".dctl" / ".png" (legacy lutExtension). */
  extension: string;
  /** PNG sub-layout (only meaningful when extension === ".png"). */
  layout: LutLayout;
  /** Cube edge size to resample to before writing. */
  size: number;
  /** Base file name / LUT title embedded in headers. */
  title: string;
  colorSpace?: ExportColorSpace;
  gammaCurve?: "kalar" | "native";
};

export type LutWriteResult = { blob: Blob; mimeType: string };

const OCTET = "application/octet-stream";

function clamp01(v: number): number {
  if (!Number.isFinite(v)) return 0;
  return v < 0 ? 0 : v > 1 ? 1 : v;
}

/** Cube edge size from a flat RGB array length (legacy `wt`). */
function cubeRoot(lengthOver3: number): number {
  return Math.round(Math.cbrt(lengthOver3));
}

/** Resample the baked grid to `size` (legacy `dm` — trilinear + clamp, r-fastest order). */
function resample(baked: BakedLUTReadback, size: number): Float32Array {
  return lutDataFromBakedLUT(baked, size).data;
}

function textFile(content: string, mimeType = OCTET): LutWriteResult {
  return { blob: new Blob([content], { type: mimeType }), mimeType };
}

// ── .cube (legacy mm) ────────────────────────────────────────────────────────
function writeCube(
  data: Float32Array,
  size: number,
  title: string,
  variant: "generic" | "c4d" = "generic",
): LutWriteResult {
  // Redshift's documented CUBE variant uses comment metadata and omits TITLE /
  // DOMAIN directives. This mirrors the legacy `cube-c4d` writer mode.
  const lines = variant === "c4d" ? [
    `# ${title}`,
    "# Created with Hytic for Cinema 4D / Redshift",
    "",
    `LUT_3D_SIZE ${size}`,
  ] : [
    "",
    `TITLE "${title} - Created with Hytic"`,
    "",
    `LUT_3D_SIZE ${size}`,
    "",
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0",
    "",
  ];
  for (let i = 0; i < data.length; i += 3) {
    lines.push(`${data[i].toFixed(6)} ${data[i + 1].toFixed(6)} ${data[i + 2].toFixed(6)}`);
  }
  lines.push("");
  return textFile(lines.join("\n"));
}

// ── .cms — Nucoda (legacy _m) ─────────────────────────────────────────────────
function writeCms(data: Float32Array, size: number, title: string): LutWriteResult {
  const lines = [
    "# Created with Hytic",
    "",
    "NUCODA_3D_CUBE 3",
    "",
    `TITLE ${title}`,
    `LUT_3D_SIZE ${size}`,
    "",
  ];
  for (let i = 0; i < data.length; i += 3) {
    lines.push(`${data[i].toFixed(6)} ${data[i + 1].toFixed(6)} ${data[i + 2].toFixed(6)}`);
  }
  lines.push("");
  return textFile(lines.join("\n"));
}

// ── .clut — Canon (legacy vm) ─────────────────────────────────────────────────
function writeCanonClut(data: Float32Array, size: number, title: string): LutWriteResult {
  const lines = [
    "# Canon LUT File",
    "# Generated by Hytic",
    "type gamut",
    `size ${size}`,
    "bit  32F",
    "order  bottom",
    "interval Equal",
    `name ${title}`,
    "values",
  ];
  for (let i = 0; i < data.length; i += 3) {
    lines.push(`${data[i].toFixed(8)} ${data[i + 1].toFixed(8)} ${data[i + 2].toFixed(8)}`);
  }
  return textFile(lines.join("\n"));
}

// ── .spi3d — OCIO (legacy wm) ─────────────────────────────────────────────────
function writeSpi3d(data: Float32Array, size: number): LutWriteResult {
  const lines = ["SPILUT 1.0", "3 3", `${size} ${size} ${size}`];
  for (let r = 0; r < size; r += 1) {
    for (let g = 0; g < size; g += 1) {
      for (let b = 0; b < size; b += 1) {
        const i = 3 * (r + g * size + b * size * size);
        lines.push(
          `${r} ${g} ${b} ${data[i].toFixed(8)} ${data[i + 1].toFixed(8)} ${data[i + 2].toFixed(8)}`,
        );
      }
    }
  }
  return textFile(lines.join("\n"));
}

// ── .txt — eeColor (legacy bm) ────────────────────────────────────────────────
function writeEeColorTxt(data: Float32Array, size: number): LutWriteResult {
  const lines: string[] = [];
  const s = size - 1;
  for (let n = 0; n < size; n += 1) {
    const a = (n / s).toFixed(6);
    for (let r = 0; r < size; r += 1) {
      const l = (r / s).toFixed(6);
      for (let c = 0; c < size; c += 1) {
        const h = (c / s).toFixed(6);
        const u = 3 * ((n * size + c) * size + r);
        lines.push(
          `${l} ${h} ${a} ${data[u].toFixed(6)} ${data[u + 1].toFixed(6)} ${data[u + 2].toFixed(6)}`,
        );
      }
    }
  }
  return textFile(lines.join("\n"));
}

// .csv (legacy xm, internal/non-UI path).
function writeCsv(data: Float32Array): LutWriteResult {
  return textFile(Array.from(data, (value) => value.toFixed(6)).join(","));
}

// ── .vlt — Panasonic Varicam (legacy Cm), always 17³, 12-bit values ───────────
function writeVlt(baked: BakedLUTReadback, title: string): LutWriteResult {
  const data = resample(baked, 17);
  const lines = [
    "# panasonic vlt file version 1.0",
    `# source vlt file "${title}.vlt"`,
    "LUT_3D_SIZE 17",
    "",
  ];
  const q = (v: number) => Math.min(4095, Math.max(0, Math.round(4095 * v))).toString();
  for (let i = 0; i < data.length; i += 3) {
    lines.push(`${q(data[i])} ${q(data[i + 1])} ${q(data[i + 2])}`);
  }
  return textFile(lines.join("\n"));
}

// ── .dctl — DaVinci (legacy Im) ───────────────────────────────────────────────
function randomLutName(): string {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let s = "";
  for (let i = 0; i < 7; i += 1) s += alphabet[Math.floor(Math.random() * alphabet.length)];
  return `LUT${s}`;
}

function writeDctl(data: Float32Array, size: number): LutWriteResult {
  const name = randomLutName();
  const body = ["", `LUT_3D_SIZE ${size}`, "LUT_3D_INPUT_RANGE 0.0 1.0", ""];
  for (let i = 0; i < data.length; i += 3) {
    body.push(`${data[i].toFixed(8)} ${data[i + 1].toFixed(8)} ${data[i + 2].toFixed(8)}`);
  }
  const content = `
    DEFINE_UI_PARAMS(p_Enable, Enable, DCTLUI_CHECK_BOX, 1)
    DEFINE_UI_PARAMS(p_Hue, Hue, DCTLUI_SLIDER_FLOAT, 1, 0, 1, 0.001)
    DEFINE_UI_PARAMS(p_Saturation, Saturation, DCTLUI_SLIDER_FLOAT, 1, 0, 1, 0.001)
    DEFINE_UI_PARAMS(p_Value, Value, DCTLUI_SLIDER_FLOAT, 1, 0, 1, 0.001)
    DEFINE_CUBE_LUT(${name}) {
      ${body.join("\n")}
    }
    __DEVICE__ float3 rgb2hsv( float3 RGB ) {
      float3 HSV;
      float min = _fminf(_fminf(RGB.x, RGB.y), RGB.z);
      float max = _fmaxf(_fmaxf(RGB.x, RGB.y), RGB.z);
      HSV.z = max;
      float delta = max - min;
      if (max != 0.0f) {
        HSV.y = delta / max;
      } else {
        HSV.y = 0.0f;
        HSV.x = 0.0f;
        return HSV;
      }
      if (delta == 0.0f) {
        HSV.x = 0.0f;
      } else if (RGB.x == max) {
        HSV.x = (RGB.y - RGB.z) / delta;
      } else if (RGB.y == max) {
        HSV.x = 2.0f + (RGB.z - RGB.x) / delta;
      } else {
        HSV.x = 4.0f + (RGB.x - RGB.y) / delta;
      }
      HSV.x *= 1.0f / 6.0f;
      if (HSV.x < 0.0f)
        HSV.x += 1.0f;
      return HSV;
    }
    __DEVICE__ float3 hsv2rgb(float3 HSV) {
      float3 RGB;
      if (HSV.y == 0.0f) {
        RGB.x = RGB.y = RGB.z = HSV.z;
      } else {
        HSV.x *= 6.0f;
        int i = floor(HSV.x);
        float f = HSV.x - i;
        i = (i >= 0) ? (i % 6) : (i % 6) + 6;
        float p = HSV.z * (1.0f - HSV.y);
        float q = HSV.z * (1.0f - HSV.y * f);
        float t = HSV.z * (1.0f - HSV.y * (1.0f - f));
        RGB.x = i == 0 ? HSV.z : i == 1 ? q : i == 2 ? p : i == 3 ? p : i == 4 ? t : HSV.z;
        RGB.y = i == 0 ? t : i == 1 ? HSV.z : i == 2 ? HSV.z : i == 3 ? q : i == 4 ? p : p;
        RGB.z = i == 0 ? p : i == 1 ? p : i == 2 ? t : i == 3 ? HSV.z : i == 4 ? HSV.z : q;
      }
      return RGB;
    }
    __DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, float p_R, float p_G, float p_B) {
      float3 rgbIn = make_float3(p_R, p_G, p_B);
      if (p_Enable) {
        float3 inHSV = rgb2hsv(rgbIn);
        float3 ltf1 = APPLY_LUT(p_R, p_G, p_B, ${name});
        float3 ltf2 = rgb2hsv(ltf1);
        float dHue = inHSV.x - ltf2.x;
        if (dHue > 0.5f) dHue -= 1.0f;
        else if (dHue < -0.5f) dHue += 1.0f;
        ltf2.x = inHSV.x - dHue * p_Hue;
        ltf2.y = _mix(inHSV.y, ltf2.y, p_Saturation);
        ltf2.z = _mix(inHSV.z, ltf2.z, p_Value);
        float3 res = hsv2rgb(ltf2);
        return res;
      } else {
        return rgbIn;
      }
    }
  `.trim();
  return textFile(content);
}

// ── PNG textures (legacy ym / Mm / Sm / Lm / Tm / Am / Em) ─────────────────────
type PngDims = { width: number; height: number; cols: number; rows: number };
const PNG_DIMS = new Map<number, PngDims>([
  [16, { width: 64, height: 64, cols: 4, rows: 4 }],
  [32, { width: 256, height: 128, cols: 8, rows: 4 }],
  [64, { width: 512, height: 512, cols: 8, rows: 8 }],
]);

/** RGB float → RGBA float with alpha 1 (legacy Mm). */
function toRGBA(rgb: Float32Array): Float32Array {
  const n = rgb.length / 3;
  const out = new Float32Array(n * 4);
  for (let i = 0, o = 0; i < rgb.length; i += 3, o += 4) {
    out[o] = rgb[i];
    out[o + 1] = rgb[i + 1];
    out[o + 2] = rgb[i + 2];
    out[o + 3] = 1;
  }
  return out;
}

/** Float RGBA (0..1) → PNG Blob at width×height (legacy Sm). */
async function pixelsToPng(rgba: Float32Array, width: number, height: number): Promise<Blob> {
  const image = new ImageData(width, height);
  for (let i = 0; i < rgba.length; i += 1) image.data[i] = 255 * clamp01(rgba[i]);

  if (typeof OffscreenCanvas !== "undefined") {
    const canvas = new OffscreenCanvas(width, height);
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Unable to create OffscreenCanvas for LUT PNG export");
    ctx.putImageData(image, 0, 0);
    return canvas.convertToBlob({ type: "image/png" });
  }

  if (typeof document === "undefined") {
    throw new Error("PNG LUT export requires canvas support in this environment");
  }
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Unable to create canvas for LUT PNG export");
  ctx.putImageData(image, 0, 0);
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => blob ? resolve(blob) : reject(new Error("Unable to encode LUT PNG")),
      "image/png",
    );
  });
}

/** Grid reorder (legacy Lm with order "xyz"): cube → cols×rows tiles of size×size B-slices. */
function gridReorder(data: Float32Array): Float32Array {
  const size = cubeRoot(data.length / 3);
  const dims = PNG_DIMS.get(size);
  if (!dims) throw new Error(`Unsupported PNG LUT size ${size}`);
  const { width, height, cols } = dims;
  const sq = size * size;
  const out = new Float32Array(width * height * 3);
  const clamped = Float32Array.from(data, clamp01);
  let w = 0;
  for (let f = 0; f < height; f += 1) {
    const tileRow = Math.floor(f / size);
    const sy = f % size;
    for (let d = 0; d < width; d += 1) {
      const tileCol = Math.floor(d / size);
      const sx = d % size;
      const sz = tileRow * cols + tileCol;
      const idx = 3 * (sx + size * sy + sq * sz);
      out[w] = clamped[idx];
      out[w + 1] = clamped[idx + 1];
      out[w + 2] = clamped[idx + 2];
      w += 3;
    }
  }
  return out;
}

/** Strip reorder (legacy Em inner reorder of the grid array, order "xzy") → size²×size. */
function stripReorder(grid: Float32Array): Float32Array {
  const size = cubeRoot(grid.length / 3);
  const dims = PNG_DIMS.get(size);
  if (!dims) throw new Error(`Unsupported PNG LUT size ${size}`);
  const { width, cols } = dims;
  const total = size * size * size;
  const clamped = Float32Array.from(grid, clamp01);
  const out = new Float32Array(total * 3);
  let w = 0;
  for (let g = 0; g < total; g += 1) {
    const n = Math.floor(g / size);
    const sx = g % size;
    const sz = n % size;
    const sy = Math.floor(n / size);
    const tileCol = sz % cols;
    const tileRow = Math.floor(sz / cols);
    const colPix = tileCol * size + sx;
    const rowPix = tileRow * size + sy;
    const m = 3 * (rowPix * width + colPix);
    out[w] = clamped[m];
    out[w + 1] = clamped[m + 1];
    out[w + 2] = clamped[m + 2];
    w += 3;
  }
  return out;
}

async function writePngLayout(
  data: Float32Array,
  size: number,
  layout: LutLayout,
): Promise<LutWriteResult> {
  const dims = PNG_DIMS.get(size);
  if (!dims) throw new Error(`PNG LUT export supports sizes 16/32/64 (got ${size}).`);
  if (layout === "cube") {
    // Hald CLUT (legacy Tm): raw cube packed row-major into the ym-sized image.
    const blob = await pixelsToPng(toRGBA(data), dims.width, dims.height);
    return { blob, mimeType: "image/png" };
  }
  if (layout === "grid") {
    const blob = await pixelsToPng(toRGBA(gridReorder(data)), dims.width, dims.height);
    return { blob, mimeType: "image/png" };
  }
  // strip: legacy Em reorders the grid array, then writes a size²×size image.
  const blob = await pixelsToPng(toRGBA(stripReorder(gridReorder(data))), size * size, size);
  return { blob, mimeType: "image/png" };
}

/**
 * Dispatch a baked global-color LUT to the requested destination writer (legacy `Go`).
 * Resamples to `size` per writer and returns the encoded Blob + MIME type.
 */
export async function writeLUT(
  baked: BakedLUTReadback,
  settings: LutWriteSettings,
): Promise<LutWriteResult> {
  const { extension, layout, size, title } = settings;
  switch (extension) {
    case ".cube":
      return writeCube(resample(baked, size), size, title, layout === "c4d" ? "c4d" : "generic");
    case ".cms":
      return writeCms(resample(baked, size), size, title);
    case ".clut":
      return writeCanonClut(resample(baked, size), size, title);
    case ".spi3d":
      return writeSpi3d(resample(baked, size), size);
    case ".txt":
      return writeEeColorTxt(resample(baked, size), size);
    case ".csv":
      return writeCsv(resample(baked, size));
    case ".vlt":
      return writeVlt(baked, title);
    case ".dctl":
      return writeDctl(resample(baked, size), size);
    case ".png":
      return writePngLayout(resample(baked, size), size, layout);
    case ".xmp":
      return {
        blob: await encodeXmpProfile(
          (await writeCube(resample(baked, size), size, title)).blob,
          title,
        ),
        mimeType: OCTET,
      };
    default:
      throw new Error(`Unsupported LUT format "${extension}".`);
  }
}
